name: build-warnings

# Controls when the action will run.
on:
  workflow_call:

jobs:
  build-warnings:
    runs-on: ubuntu-latest
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"

    steps:

      - name: Checkout ss repo
        uses: actions/checkout@v2

      - name: setup R
        uses: r-lib/actions/setup-r@master

      - name: Get admb and put in path
        run: |
          wget https://github.com/admb-project/admb/releases/download/admb-12.3/admb-12.3-linux.zip
          sudo unzip admb-12.3-linux.zip -d /usr/local/bin
          sudo chmod 755 /usr/local/bin/admb-12.3/bin/admb
          echo "/usr/local/bin/admb-12.3/bin" >> $GITHUB_PATH

      - name: Build stock synthesis with warnings
        run: |
          rm -rf SS330
          mkdir SS330
          /bin/bash ./Make_SS_330_new.sh -a /usr/local/bin/admb-12.3 -b SS330 -w &> warnings.txt
      # Runs a set of commands using the runners shell
      - name: Use R to parse warnings output
        run: |
          txt <- readLines("warnings.txt", encoding = "UTF-8" )
          warn_line <- grep(pattern = "compiling a second time to get warnings",
            x = txt,
            fixed = TRUE)
          txt <- txt[(warn_line+1):length(txt)]
          rm_warn_start_lines <- grep(pattern = "/usr/local/bin/admb-12.3", x = txt,
            fixed = TRUE)
          all_warning_end_lines <- grep(pattern = "^", x = txt, fixed = TRUE)
          to_rm <- NULL
          for (l in rm_warn_start_lines) {
            tmp_end_line <- min(all_warning_end_lines[all_warning_end_lines > l])
            to_rm <- c(to_rm, l:tmp_end_line)
          }
          txt <- txt[-to_rm]
          n_errors <- length(grep(pattern = "^", x = txt, fixed = TRUE))
          message("There are ", n_errors, " warning messages related to SS.")
          write.table(n_errors, "n_warn.txt")
          writeLines(txt, "warnings_ss.txt")
        shell: Rscript {0}

      - name:  Print warnings
        run: cat warnings_ss.txt

      - name: determine if fails/passes
        run: |
          n_warn <- read.table("n_warn.txt")
          n_warn <- as.integer(n_warn[1,1])
          if (n_warn > 83) {
            stop("Increased number of warnings")
          } else {
            message("Acceptable number of warnings")
          }
        shell: Rscript {0}

      - name: Archive warnings text file
        if: always()
        uses: actions/upload-artifact@main
        with:
          name: 'warnings_ss.txt'
          path: warnings_ss.txt

