# Run r cmd check
on:
  push:
   paths-ignore:
     - '.github/workflows/call**'
  pull_request:
    paths-ignore:
      - '.github/workflows/call**'
  schedule:
    # This should run the default branch weekly on sunday
    - cron: '0 0 * * 0'
name: call-r-cmd-check

jobs:
  call-workflow:
    uses: nmfs-stock-synthesis/workflows/.github/workflows/r-cmd-check.yml@main
