# Extra run of r4ss tests, when exe and models in test-models are available.workflow_call
# stored in this repo because only applicable to ss3 (and in particular r4ss)

on:
  workflow_call:
    inputs:
      run-codecov:
        required: false
        type: boolean
        default: false

name: run-tests
jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, r: 'release', rspm: 'https://packagemanager.rstudio.com/cran/__linux__/focal/latest'}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::covr
            any::devtools

      - name: Get repository of SS models
        uses: actions/checkout@v3
        with:
          repository: 'nmfs-stock-synthesis/test-models'
          path: test-models-repo

      - name: move the models to the desired location
        run: |
          mv test-models-repo/models inst/extdata
          rm  -rf test-models-repo
          ls inst/extdata

      - name: Get the latest SS3 executable and move to expected location
        run: |
          curl https://api.github.com/repos/nmfs-stock-synthesis/stock-synthesis/releases/latest | grep "browser_download_url" | grep -Eo 'https://[^\"]*' | grep "ss_linux" | xargs wget
          mv ss_linux ss
          sudo chmod a+x ss
          cp ss inst/extdata/simple_small/ss
          rm ss

      - name: Get a 3.24 SS executable
        run: |
          wget -O ss https://vlab.noaa.gov/documents/259399/2000201/ss_3.24Z/037e3921-1f00-611a-1c30-d7a5c1063835?version=1.1&t=1608655599519&download=true
          sudo chmod a+x ss
          mv ss inst/extdata/simple_3.24/ss
          
      - name: Test
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        if: inputs.run-codecov != true
        run: devtools::test(stop_on_failure = TRUE)
        shell: Rscript {0}
        
      - name: Test coverage
        if: inputs.run-codecov == true
        run: covr::codecov()
        shell: Rscript {0}
