# Check mcmc works
name: run-ss3-mcmc

on:
  workflow_call:

jobs:
  run-no-est:
    runs-on: ubuntu-latest
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"

    steps:

      - name: Checkout ss repo
        uses: actions/checkout@v2


      - name: Checkout models repo
        uses: actions/checkout@v2
        with:
          repository: 'nmfs-stock-synthesis/test-models'
          path: test-models-repo

      - name: setup R
        uses: r-lib/actions/setup-r@master

      - name: Get admb and put in path, linux
        run: |
          wget https://github.com/admb-project/admb/releases/download/admb-13.0/admb-13.0-linux.zip
          sudo unzip admb-13.0-linux.zip -d /usr/local/bin
          sudo chmod 755 /usr/local/bin/admb-13.0/bin/admb
          echo "/usr/local/bin/admb-13.0/bin" >> $GITHUB_PATH

      - name: Build stock synthesis
        run: |
          rm -rf SS330
          mkdir SS330
          /bin/bash ./Make_SS_330_new.sh -b SS330

      - name: move exes, scripts to needed locations
        run: |
          mv test-models-repo/models/Simple/starter.ss starter.ss
          mv test-models-repo/models/Simple/forecast.ss forecast.ss
          mv test-models-repo/models/Simple/control.ss control.ss
          mv test-models-repo/models/Simple/data.ss data.ss
          mv SS330/ss ss
          ls

      - name: change permissions on ss exe
        run: chmod a+x ss

      - name: run models without estimation
        run: |
          # Run NUTS algorithim in ADMB to make sure still works with stock synthesis
          # run the simple model with -hbf option to get the necessary files
          system("./ss -hbf")
          # run the simple model 30 times using the NUTS algorithim
          niters <- 100
          for (i in 1:niters) {
            message("Running iteration ", i)
            # run simple model
            system("./ss  -maxfn 0 -phase 40 -nohess -mcmc 10 -nuts -mcseed 1 -max_treedepth 3")
            # read in adaption.csv
            adapt_df <- read.csv("adaptation.csv")
            if(i == 1) {
              compare_val <- adapt_df[nrow(adapt_df), "stepsize__"]
              message("Getting ref value from iteration ", i, ". Ref value is " ,
                      compare_val)
            } else {
              message("Checking iteration ", i)
              val_to_check <- adapt_df[nrow(adapt_df), "stepsize__"]
            	if(!identical(val_to_check, compare_val)) {
                stop("First step size for iteration ", i ," (step size =",
                     val_to_check,
                     ")", " was not equal to values in the first iteration (",
                     compare_val, ").")
            	}
            }
          }
          message("No differences in step size among stock synthesis runs.")
        shell: Rscript {0}


