FROM rocker/r-ver
MAINTAINER Stock Synthesis Team <nmfs.stock.synthesis@noaa.gov>

RUN apt-get update
RUN chmod 777 /usr/local/lib/R/site-library
RUN apt-get -y install libxml2-dev
RUN apt-get -y install libcurl4-openssl-dev
RUN apt-get -y install libssl-dev
